import { z } from 'zod';

// ---------------------------------------------------------------------------
// Enum constants (matching Prisma-generated JournalSource / JournalStatus)
// ---------------------------------------------------------------------------

export const JOURNAL_SOURCES = [
  'MANUAL',
  'AR_INVOICE',
  'AR_CREDIT_NOTE',
  'AR_PAYMENT',
  'AP_BILL',
  'AP_CREDIT_NOTE',
  'AP_PAYMENT',
  'BANK_PAYMENT',
  'BANK_RECEIPT',
  'BANK_TRANSFER',
  'STOCK_MOVEMENT',
  'STOCK_REVALUATION',
  'GOODS_RECEIPT',
  'SHIPMENT',
  'DEPRECIATION',
  'PAYROLL',
  'PRODUCTION',
  'VAT_ADJUSTMENT',
  'YEAR_END',
  'OPENING_BALANCE',
] as const;

export const JOURNAL_STATUSES = ['DRAFT', 'POSTED', 'REVERSED'] as const;

// ---------------------------------------------------------------------------
// Shared line schemas
// ---------------------------------------------------------------------------

const journalLineDimensionInputSchema = z.object({
  dimensionValueId: z.uuid(),
});

const journalLineInputSchema = z.object({
  accountCode: z.string().min(2).max(20),
  description: z.string().max(500).optional(),
  debit: z.number().min(0).default(0),
  credit: z.number().min(0).default(0),
  vatCode: z.string().max(20).optional(),
  currencyCode: z.string().max(3).optional(),
  foreignAmount: z.number().optional(),
  exchangeRate: z.number().optional(),
  dimensions: z.array(journalLineDimensionInputSchema).optional(),
});

// ---------------------------------------------------------------------------
// Request Schemas
// ---------------------------------------------------------------------------

export const createJournalSchema = z.object({
  transactionDate: z.coerce.date(),
  description: z.string().min(1, 'Description is required').max(500),
  reference: z.string().max(100).optional(),
  periodId: z.uuid(),
  lines: z.array(journalLineInputSchema).min(2, 'Journal entry must have at least 2 lines'),
});

export const updateJournalSchema = z
  .object({
    transactionDate: z.coerce.date().optional(),
    description: z.string().min(1).max(500).optional(),
    reference: z.string().max(100).nullable().optional(),
    periodId: z.uuid().optional(),
    lines: z
      .array(journalLineInputSchema)
      .min(2, 'Journal entry must have at least 2 lines')
      .optional(),
  })
  .refine((data) => Object.values(data).some((v) => v !== undefined), {
    message: 'At least one field must be provided for update',
  });

// ---------------------------------------------------------------------------
// Params & Query Schemas
// ---------------------------------------------------------------------------

export const journalParamsSchema = z.object({
  id: z.uuid(),
});

export const listJournalsQuerySchema = z.object({
  status: z.enum(JOURNAL_STATUSES).optional(),
  source: z.enum(JOURNAL_SOURCES).optional(),
  periodId: z.uuid().optional(),
  dateFrom: z.coerce.date().optional(),
  dateTo: z.coerce.date().optional(),
  cursor: z.uuid().optional(),
  limit: z.coerce.number().int().min(1).max(500).default(50),
});

export const searchJournalsQuerySchema = z.object({
  search: z.string().min(1, 'Search term is required'),
  status: z.enum(JOURNAL_STATUSES).optional(),
  source: z.enum(JOURNAL_SOURCES).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});

// ---------------------------------------------------------------------------
// Response Schemas
// ---------------------------------------------------------------------------

const journalLineDimensionResponseSchema = z.object({
  id: z.string(),
  dimensionValueId: z.string(),
  dimensionValue: z
    .object({
      id: z.string(),
      code: z.string(),
      name: z.string(),
      dimensionType: z.object({
        id: z.string(),
        code: z.string(),
        name: z.string(),
      }),
    })
    .optional(),
});

const journalLineResponseSchema = z.object({
  id: z.string(),
  lineNumber: z.number(),
  accountCode: z.string(),
  description: z.string().nullable(),
  debit: z.number(),
  credit: z.number(),
  vatCode: z.string().nullable(),
  currencyCode: z.string().nullable(),
  foreignAmount: z.number().nullable(),
  exchangeRate: z.number().nullable(),
  dimensions: z.array(journalLineDimensionResponseSchema).optional(),
});

export const journalListItemSchema = z.object({
  id: z.uuid(),
  entryNumber: z.string(),
  transactionDate: z.string(),
  description: z.string(),
  reference: z.string().nullable(),
  source: z.enum(JOURNAL_SOURCES),
  sourceReference: z.string().nullable(),
  status: z.enum(JOURNAL_STATUSES),
  periodId: z.string(),
  totalDebit: z.number(),
  totalCredit: z.number(),
  postedAt: z.string().nullable(),
  postedBy: z.string().nullable(),
  reversalOfId: z.string().nullable(),
  isAutoGenerated: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export const journalDetailSchema = journalListItemSchema.extend({
  sourceId: z.string().nullable(),
  templateId: z.string().nullable(),
  createdBy: z.string(),
  updatedBy: z.string(),
  lines: z.array(journalLineResponseSchema),
});

// ---------------------------------------------------------------------------
// Inferred TypeScript Types
// ---------------------------------------------------------------------------

export type CreateJournalInput = z.infer<typeof createJournalSchema>;
export type UpdateJournalInput = z.infer<typeof updateJournalSchema>;
export type ListJournalsQuery = z.infer<typeof listJournalsQuerySchema>;
export type SearchJournalsQuery = z.infer<typeof searchJournalsQuerySchema>;
export type JournalLineInput = z.infer<typeof journalLineInputSchema>;
