import type { PrismaClient } from '@nexa/db';
import { Prisma, nextNumber } from '@nexa/db';

// JournalSource enum type — Prisma requires the enum, not a plain string.
// We cast at the boundary where sub-modules pass string source values.
type JournalSourceEnum =
  | 'MANUAL'
  | 'AR_INVOICE'
  | 'AR_CREDIT_NOTE'
  | 'AR_PAYMENT'
  | 'AP_BILL'
  | 'AP_CREDIT_NOTE'
  | 'AP_PAYMENT'
  | 'BANK_PAYMENT'
  | 'BANK_RECEIPT'
  | 'BANK_TRANSFER'
  | 'STOCK_MOVEMENT'
  | 'STOCK_REVALUATION'
  | 'GOODS_RECEIPT'
  | 'SHIPMENT'
  | 'DEPRECIATION'
  | 'PAYROLL'
  | 'PRODUCTION'
  | 'VAT_ADJUSTMENT'
  | 'YEAR_END'
  | 'OPENING_BALANCE';
import type {
  CreateJournalInput,
  UpdateJournalInput,
  ListJournalsQuery,
  SearchJournalsQuery,
} from './journals.schema.js';
import { AppError, DomainError, NotFoundError } from '../../core/errors/index.js';
import type { EventBus } from '../../core/events/event-bus.js';
import type { PaginationMeta } from '../../core/utils/response.js';
import { convertLinesToBaseCurrency, getBaseCurrencyCode } from './multi-currency.service.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GlPostingInput {
  transactionDate: Date;
  description: string;
  reference?: string;
  source: string; // JournalSource enum value
  sourceId?: string;
  sourceReference?: string;
  lines: Array<{
    accountCode: string;
    debit: number;
    credit: number;
    description?: string;
    vatCode?: string;
    currencyCode?: string;
    foreignAmount?: number;
    exchangeRate?: number;
    dimensions?: Array<{ dimensionValueId: string }>;
  }>;
}

// ---------------------------------------------------------------------------
// Prisma select shapes
// ---------------------------------------------------------------------------

const LINE_DIMENSION_SELECT = {
  id: true,
  dimensionValueId: true,
  dimensionValue: {
    select: {
      id: true,
      code: true,
      name: true,
      dimensionType: {
        select: {
          id: true,
          code: true,
          name: true,
        },
      },
    },
  },
} as const;

const LINE_SELECT = {
  id: true,
  lineNumber: true,
  accountCode: true,
  description: true,
  debit: true,
  credit: true,
  vatCode: true,
  currencyCode: true,
  foreignAmount: true,
  exchangeRate: true,
  dimensions: { select: LINE_DIMENSION_SELECT },
} as const;

const LIST_SELECT = {
  id: true,
  entryNumber: true,
  transactionDate: true,
  description: true,
  reference: true,
  source: true,
  sourceReference: true,
  status: true,
  periodId: true,
  totalDebit: true,
  totalCredit: true,
  postedAt: true,
  postedBy: true,
  reversalOfId: true,
  isAutoGenerated: true,
  createdAt: true,
  updatedAt: true,
} as const;

const DETAIL_SELECT = {
  ...LIST_SELECT,
  sourceId: true,
  templateId: true,
  createdBy: true,
  updatedBy: true,
  lines: {
    select: LINE_SELECT,
    orderBy: { lineNumber: 'asc' as const },
  },
} as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert Prisma Decimal fields to numbers for JSON serialisation */
function toNumber(val: Prisma.Decimal | number | null | undefined): number {
  if (val === null || val === undefined) return 0;
  return typeof val === 'number' ? val : Number(val);
}

/** Extract YYYY-MM-DD from a Date */
function toDateString(d: Date | string): string {
  if (typeof d === 'string') return d.slice(0, 10);
  return d.toISOString().slice(0, 10);
}

/** Normalise a journal line for API response */
function normaliseLine(line: Record<string, unknown>) {
  return {
    ...line,
    debit: toNumber(line.debit as Prisma.Decimal),
    credit: toNumber(line.credit as Prisma.Decimal),
    foreignAmount: line.foreignAmount ? toNumber(line.foreignAmount as Prisma.Decimal) : null,
    exchangeRate: line.exchangeRate ? toNumber(line.exchangeRate as Prisma.Decimal) : null,
  };
}

/** Normalise a journal list item for API response */
function normaliseListItem(row: Record<string, unknown>) {
  return {
    ...row,
    transactionDate:
      row.transactionDate instanceof Date
        ? toDateString(row.transactionDate)
        : String(row.transactionDate),
    totalDebit: toNumber(row.totalDebit as Prisma.Decimal),
    totalCredit: toNumber(row.totalCredit as Prisma.Decimal),
    postedAt:
      row.postedAt instanceof Date ? row.postedAt.toISOString() : (row.postedAt as string | null),
  };
}

/** Normalise a journal detail for API response */
function normaliseDetail(row: Record<string, unknown>) {
  const lines = (row.lines as Array<Record<string, unknown>> | undefined) ?? [];
  return {
    ...normaliseListItem(row),
    lines: lines.map(normaliseLine),
  };
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

/**
 * Validate that a period exists, belongs to the company, and is OPEN.
 * Returns the period row. Throws DomainError for CLOSED/LOCKED (BR-FIN-003).
 */
async function validatePeriodForPosting(
  tx: Parameters<Parameters<PrismaClient['$transaction']>[0]>[0],
  companyId: string,
  periodId: string,
) {
  const period = await tx.financialPeriod.findFirst({
    where: { id: periodId, companyId },
    select: { id: true, status: true, fiscalYear: true, periodNumber: true },
  });

  if (!period) {
    throw new NotFoundError('PERIOD_NOT_FOUND', 'Financial period not found');
  }

  if (period.status === 'CLOSED' || period.status === 'LOCKED') {
    throw new DomainError(
      'PERIOD_NOT_OPEN',
      `Cannot post to ${period.status.toLowerCase()} period (BR-FIN-003)`,
    );
  }

  return period;
}

/**
 * Validate all account codes in lines exist, are active, postable, and not control accounts.
 * BR-FIN-013: Cannot manually post to AR/AP control accounts.
 * BR-FIN-013: Cannot post to non-postable accounts (isPostable=false).
 */
async function validateAccountsForPosting(
  tx: Parameters<Parameters<PrismaClient['$transaction']>[0]>[0],
  companyId: string,
  accountCodes: string[],
  isManual: boolean,
) {
  const uniqueCodes = [...new Set(accountCodes)];
  const accounts = await tx.chartOfAccount.findMany({
    where: { companyId, code: { in: uniqueCodes } },
    select: { code: true, isActive: true, isPostable: true, isControl: true },
  });

  const foundCodes = new Set(accounts.map((a) => a.code));
  for (const code of uniqueCodes) {
    if (!foundCodes.has(code)) {
      throw new AppError('ACCOUNT_NOT_FOUND', `Account code "${code}" not found`, 400);
    }
  }

  for (const account of accounts) {
    if (!account.isActive) {
      throw new DomainError(
        'ACCOUNT_INACTIVE',
        `Account "${account.code}" is inactive and cannot be posted to`,
      );
    }
    if (!account.isPostable) {
      throw new DomainError(
        'ACCOUNT_NOT_POSTABLE',
        `Account "${account.code}" is not postable (BR-FIN-013)`,
      );
    }
    if (isManual && account.isControl) {
      throw new DomainError(
        'CONTROL_ACCOUNT_MANUAL_POST',
        `Cannot manually post to control account "${account.code}" (BR-FIN-013)`,
      );
    }
  }
}

/**
 * Enforce DimensionRequirement rules on posting (AC-12).
 * For each line, check if the account is in any DimensionRequirement range.
 * If so, the line must have a dimension of that type.
 */
async function validateDimensionRequirements(
  tx: Parameters<Parameters<PrismaClient['$transaction']>[0]>[0],
  companyId: string,
  lines: Array<{
    accountCode: string;
    dimensions?: Array<{ dimensionValueId: string }>;
  }>,
) {
  // Get all active dimension requirements for this company
  const requirements = await tx.dimensionRequirement.findMany({
    where: { companyId, isActive: true, isRequired: true },
    select: {
      dimensionTypeId: true,
      accountCodeFrom: true,
      accountCodeTo: true,
      dimensionType: { select: { code: true, name: true } },
    },
  });

  if (requirements.length === 0) return;

  // Get dimension value → type mappings for all dimension values in lines
  const allDimValueIds = lines
    .flatMap((l) => (l.dimensions ?? []).map((d) => d.dimensionValueId))
    .filter(Boolean);

  const dimValues =
    allDimValueIds.length > 0
      ? await tx.dimensionValue.findMany({
          where: { id: { in: allDimValueIds } },
          select: { id: true, dimensionTypeId: true },
        })
      : [];

  const dimValueTypeMap = new Map(dimValues.map((v) => [v.id, v.dimensionTypeId]));

  for (const line of lines) {
    for (const req of requirements) {
      // Check if account code falls within the requirement range
      if (line.accountCode >= req.accountCodeFrom && line.accountCode <= req.accountCodeTo) {
        // This account requires a dimension of this type
        const lineDimTypeIds = (line.dimensions ?? [])
          .map((d) => dimValueTypeMap.get(d.dimensionValueId))
          .filter(Boolean);

        if (!lineDimTypeIds.includes(req.dimensionTypeId)) {
          throw new DomainError(
            'DIMENSION_REQUIRED',
            `Account "${line.accountCode}" requires dimension "${req.dimensionType.name}" (${req.dimensionType.code}) (BR-FIN-DIM-002)`,
          );
        }
      }
    }
  }
}

/**
 * Validate single-select constraint (BR-FIN-DIM-001).
 * For each line, check that at most one dimension value per type is assigned.
 */
async function validateSingleSelectDimensions(
  tx: Parameters<Parameters<PrismaClient['$transaction']>[0]>[0],
  lines: Array<{ dimensions?: Array<{ dimensionValueId: string }> }>,
) {
  const allDimValueIds = lines
    .flatMap((l) => (l.dimensions ?? []).map((d) => d.dimensionValueId))
    .filter(Boolean);

  if (allDimValueIds.length === 0) return;

  const dimValues = await tx.dimensionValue.findMany({
    where: { id: { in: allDimValueIds } },
    select: {
      id: true,
      dimensionTypeId: true,
      dimensionType: { select: { isSingleSelect: true, name: true } },
    },
  });

  const dimValueMap = new Map(dimValues.map((v) => [v.id, v]));

  for (const line of lines) {
    if (!line.dimensions || line.dimensions.length === 0) continue;

    const typeIdCounts = new Map<string, number>();
    for (const dim of line.dimensions) {
      const dv = dimValueMap.get(dim.dimensionValueId);
      if (!dv) {
        throw new AppError(
          'DIMENSION_VALUE_NOT_FOUND',
          `Dimension value "${dim.dimensionValueId}" not found`,
          400,
        );
      }
      if (dv.dimensionType.isSingleSelect) {
        const count = (typeIdCounts.get(dv.dimensionTypeId) ?? 0) + 1;
        typeIdCounts.set(dv.dimensionTypeId, count);
        if (count > 1) {
          throw new DomainError(
            'DIMENSION_SINGLE_SELECT',
            `Dimension "${dv.dimensionType.name}" only allows one value per line (BR-FIN-DIM-001)`,
          );
        }
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Balance update helpers
// ---------------------------------------------------------------------------

/**
 * Update ChartOfAccount.currentBalance for each affected account (AC-4).
 */
async function updateAccountBalances(
  tx: Parameters<Parameters<PrismaClient['$transaction']>[0]>[0],
  companyId: string,
  lines: Array<{ accountCode: string; debit: number; credit: number }>,
) {
  // Group by account code and compute net change
  const balanceChanges = new Map<string, number>();
  for (const line of lines) {
    const current = balanceChanges.get(line.accountCode) ?? 0;
    // debit increases, credit decreases (for assets/expenses; reversed for liabilities/equity/revenue)
    // We store raw debit-credit delta; the currentBalance field accumulates this
    balanceChanges.set(line.accountCode, current + line.debit - line.credit);
  }

  for (const [accountCode, delta] of balanceChanges) {
    if (delta === 0) continue;
    await tx.chartOfAccount.update({
      where: {
        uq_chart_of_account_company_code: { companyId, code: accountCode },
      },
      data: {
        currentBalance: { increment: delta },
      },
    });
  }
}

/**
 * Update DimensionBalance for each JournalLineDimension (AC-5, BR-FIN-DIM-007).
 * Upserts the balance row — creates if not exists, increments if exists.
 */
async function updateDimensionBalances(
  tx: Parameters<Parameters<PrismaClient['$transaction']>[0]>[0],
  companyId: string,
  periodId: string,
  lines: Array<{
    accountCode: string;
    debit: number;
    credit: number;
    dimensions?: Array<{ dimensionValueId: string }>;
  }>,
) {
  // Collect all dimension value IDs to look up their types
  const allDimValueIds = lines
    .flatMap((l) => (l.dimensions ?? []).map((d) => d.dimensionValueId))
    .filter(Boolean);

  if (allDimValueIds.length === 0) return;

  const dimValues = await tx.dimensionValue.findMany({
    where: { id: { in: [...new Set(allDimValueIds)] } },
    select: { id: true, dimensionTypeId: true },
  });

  const dimValueTypeMap = new Map(dimValues.map((v) => [v.id, v.dimensionTypeId]));

  for (const line of lines) {
    if (!line.dimensions || line.dimensions.length === 0) continue;

    for (const dim of line.dimensions) {
      const dimensionTypeId = dimValueTypeMap.get(dim.dimensionValueId);
      if (!dimensionTypeId) continue;

      // Upsert dimension balance
      await tx.dimensionBalance.upsert({
        where: {
          uq_dimension_balance: {
            companyId,
            accountCode: line.accountCode,
            dimensionTypeId,
            dimensionValueId: dim.dimensionValueId,
            periodId,
          },
        },
        create: {
          companyId,
          accountCode: line.accountCode,
          dimensionTypeId,
          dimensionValueId: dim.dimensionValueId,
          periodId,
          totalDebit: line.debit,
          totalCredit: line.credit,
        },
        update: {
          totalDebit: { increment: line.debit },
          totalCredit: { increment: line.credit },
        },
      });
    }
  }
}

// ---------------------------------------------------------------------------
// createJournalEntry (AC-1) — create a DRAFT manual journal entry
// ---------------------------------------------------------------------------

export async function createJournalEntry(
  prisma: PrismaClient,
  eventBus: EventBus,
  companyId: string,
  data: CreateJournalInput,
  userId: string,
) {
  const entry = await prisma.$transaction(async (tx) => {
    // Validate period exists and belongs to company (not enforcing OPEN for drafts)
    const period = await tx.financialPeriod.findFirst({
      where: { id: data.periodId, companyId },
      select: { id: true },
    });
    if (!period) {
      throw new NotFoundError('PERIOD_NOT_FOUND', 'Financial period not found');
    }

    // Validate all account codes exist
    const accountCodes = data.lines.map((l) => l.accountCode);
    const uniqueCodes = [...new Set(accountCodes)];
    const accounts = await tx.chartOfAccount.findMany({
      where: { companyId, code: { in: uniqueCodes } },
      select: { code: true },
    });
    const foundCodes = new Set(accounts.map((a) => a.code));
    for (const code of uniqueCodes) {
      if (!foundCodes.has(code)) {
        throw new AppError('ACCOUNT_NOT_FOUND', `Account code "${code}" not found`, 400);
      }
    }

    // Generate entry number via NumberSeries (AC-1, BR-FIN-012)
    const entryNumber = await nextNumber(tx, companyId, 'JOURNAL');

    // Multi-currency conversion (E14-S20): convert foreign currency lines to base currency
    const baseCurrencyCode = await getBaseCurrencyCode(tx, companyId);
    const convertedLines = await convertLinesToBaseCurrency(
      tx,
      companyId,
      baseCurrencyCode,
      data.transactionDate,
      data.lines.map((l) => ({
        ...l,
        debit: l.debit ?? 0,
        credit: l.credit ?? 0,
      })),
    );

    // Calculate totals from converted (base currency) amounts
    const totalDebit = convertedLines.reduce((sum, l) => sum + l.debit, 0);
    const totalCredit = convertedLines.reduce((sum, l) => sum + l.credit, 0);

    // Create journal entry
    const journalEntry = await tx.journalEntry.create({
      data: {
        companyId,
        entryNumber,
        transactionDate: data.transactionDate,
        description: data.description,
        reference: data.reference ?? null,
        source: 'MANUAL',
        status: 'DRAFT',
        periodId: data.periodId,
        totalDebit,
        totalCredit,
        createdBy: userId,
        updatedBy: userId,
      },
      select: { id: true },
    });

    // Create lines (using converted base-currency amounts)
    for (let i = 0; i < convertedLines.length; i++) {
      const line = convertedLines[i]!;
      const originalLine = data.lines[i]!;
      const createdLine = await tx.journalLine.create({
        data: {
          journalEntryId: journalEntry.id,
          lineNumber: i + 1,
          accountCode: line.accountCode,
          companyId,
          description: line.description ?? null,
          debit: line.debit,
          credit: line.credit,
          vatCode: line.vatCode ?? null,
          currencyCode: line.currencyCode ?? null,
          foreignAmount: line.foreignAmount ?? null,
          exchangeRate: line.exchangeRate ?? null,
        },
        select: { id: true },
      });

      // Create line dimensions
      if (originalLine.dimensions && originalLine.dimensions.length > 0) {
        for (const dim of originalLine.dimensions) {
          await tx.journalLineDimension.create({
            data: {
              journalLineId: createdLine.id,
              dimensionValueId: dim.dimensionValueId,
            },
          });
        }
      }
    }

    // Fetch the complete entry for response
    return tx.journalEntry.findUniqueOrThrow({
      where: { id: journalEntry.id },
      select: DETAIL_SELECT,
    });
  });

  // Emit journal.created event
  eventBus.emit('journal.created', {
    journalEntryId: entry.id,
    entryNumber: entry.entryNumber,
    companyId,
    source: 'MANUAL',
    createdBy: userId,
  });

  return normaliseDetail(entry as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// updateJournalEntry (AC-2, AC-9)
// ---------------------------------------------------------------------------

export async function updateJournalEntry(
  prisma: PrismaClient,
  _eventBus: EventBus,
  companyId: string,
  id: string,
  data: UpdateJournalInput,
  userId: string,
) {
  const entry = await prisma.$transaction(async (tx) => {
    // Fetch existing entry
    const existing = await tx.journalEntry.findFirst({
      where: { id, companyId },
      select: { id: true, status: true, source: true, transactionDate: true },
    });

    if (!existing) {
      throw new NotFoundError('NOT_FOUND', 'Journal entry not found');
    }

    // AC-9, BR-FIN-011: Cannot modify POSTED or REVERSED entry
    if (existing.status !== 'DRAFT') {
      throw new DomainError(
        'ENTRY_IMMUTABLE',
        `Cannot modify a ${existing.status} journal entry (BR-FIN-011)`,
      );
    }

    // Validate period if being changed
    if (data.periodId) {
      const period = await tx.financialPeriod.findFirst({
        where: { id: data.periodId, companyId },
        select: { id: true },
      });
      if (!period) {
        throw new NotFoundError('PERIOD_NOT_FOUND', 'Financial period not found');
      }
    }

    // If lines are being replaced, validate accounts, convert currencies, and rebuild
    let convertedLines: Array<{
      accountCode: string;
      description?: string | null;
      debit: number;
      credit: number;
      vatCode?: string | null;
      currencyCode: string | null;
      foreignAmount: number | null;
      exchangeRate: number | null;
      dimensions?: Array<{ dimensionValueId: string }>;
    }> | null = null;

    if (data.lines) {
      const accountCodes = data.lines.map((l) => l.accountCode);
      const uniqueCodes = [...new Set(accountCodes)];
      const accounts = await tx.chartOfAccount.findMany({
        where: { companyId, code: { in: uniqueCodes } },
        select: { code: true },
      });
      const foundCodes = new Set(accounts.map((a) => a.code));
      for (const code of uniqueCodes) {
        if (!foundCodes.has(code)) {
          throw new AppError('ACCOUNT_NOT_FOUND', `Account code "${code}" not found`, 400);
        }
      }

      // Multi-currency conversion (E14-S20)
      const txDate = data.transactionDate ?? existing.transactionDate ?? new Date();
      const baseCurrencyCode = await getBaseCurrencyCode(tx, companyId);
      convertedLines = await convertLinesToBaseCurrency(
        tx,
        companyId,
        baseCurrencyCode,
        txDate instanceof Date ? txDate : new Date(txDate),
        data.lines.map((l) => ({
          ...l,
          debit: l.debit ?? 0,
          credit: l.credit ?? 0,
        })),
      );

      // Delete existing lines (cascade deletes dimensions)
      await tx.journalLine.deleteMany({
        where: { journalEntryId: id },
      });

      // Create new lines with converted amounts
      for (let i = 0; i < convertedLines.length; i++) {
        const line = convertedLines[i]!;
        const originalLine = data.lines[i]!;
        const createdLine = await tx.journalLine.create({
          data: {
            journalEntryId: id,
            lineNumber: i + 1,
            accountCode: line.accountCode,
            companyId,
            description: line.description ?? null,
            debit: line.debit,
            credit: line.credit,
            vatCode: line.vatCode ?? null,
            currencyCode: line.currencyCode ?? null,
            foreignAmount: line.foreignAmount ?? null,
            exchangeRate: line.exchangeRate ?? null,
          },
          select: { id: true },
        });

        if (originalLine.dimensions && originalLine.dimensions.length > 0) {
          for (const dim of originalLine.dimensions) {
            await tx.journalLineDimension.create({
              data: {
                journalLineId: createdLine.id,
                dimensionValueId: dim.dimensionValueId,
              },
            });
          }
        }
      }
    }

    // Calculate new totals if lines changed (using converted base-currency amounts)
    const updateData: Record<string, unknown> = { updatedBy: userId };
    if (data.transactionDate !== undefined) updateData.transactionDate = data.transactionDate;
    if (data.description !== undefined) updateData.description = data.description;
    if (data.reference !== undefined) updateData.reference = data.reference;
    if (data.periodId !== undefined) updateData.periodId = data.periodId;

    if (convertedLines) {
      updateData.totalDebit = convertedLines.reduce((sum, l) => sum + l.debit, 0);
      updateData.totalCredit = convertedLines.reduce((sum, l) => sum + l.credit, 0);
    }

    await tx.journalEntry.update({
      where: { id },
      data: updateData,
    });

    // Fetch the complete updated entry
    return tx.journalEntry.findUniqueOrThrow({
      where: { id },
      select: DETAIL_SELECT,
    });
  });

  return normaliseDetail(entry as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// postJournalEntry (AC-3, AC-4, AC-5, AC-6, AC-8, AC-12, AC-13)
// ---------------------------------------------------------------------------

export async function postJournalEntry(
  prisma: PrismaClient,
  eventBus: EventBus,
  companyId: string,
  id: string,
  userId: string,
) {
  const entry = await prisma.$transaction(async (tx) => {
    // Fetch the entry with lines and dimensions
    const existing = await tx.journalEntry.findFirst({
      where: { id, companyId },
      select: {
        id: true,
        entryNumber: true,
        status: true,
        source: true,
        periodId: true,
        transactionDate: true,
        lines: {
          select: {
            accountCode: true,
            debit: true,
            credit: true,
            dimensions: { select: { dimensionValueId: true } },
          },
        },
      },
    });

    if (!existing) {
      throw new NotFoundError('NOT_FOUND', 'Journal entry not found');
    }

    // Only DRAFT can be posted
    if (existing.status !== 'DRAFT') {
      throw new DomainError(
        'INVALID_STATUS_TRANSITION',
        `Cannot post a ${existing.status} entry. Only DRAFT entries can be posted (BR-FIN-011)`,
      );
    }

    // Normalise line amounts for validation
    const lines = existing.lines.map((l) => ({
      accountCode: l.accountCode,
      debit: toNumber(l.debit as unknown as Prisma.Decimal),
      credit: toNumber(l.credit as unknown as Prisma.Decimal),
      dimensions: l.dimensions.map((d) => ({ dimensionValueId: d.dimensionValueId })),
    }));

    // BR-FIN-001: debits must equal credits
    const totalDebit = lines.reduce((sum, l) => sum + l.debit, 0);
    const totalCredit = lines.reduce((sum, l) => sum + l.credit, 0);
    // Use a small epsilon for floating-point comparison
    if (Math.abs(totalDebit - totalCredit) > 0.0001) {
      throw new DomainError(
        'ENTRY_NOT_BALANCED',
        `Journal entry is not balanced: debits (${String(totalDebit)}) != credits (${String(totalCredit)}) (BR-FIN-001)`,
      );
    }

    // AC-8, BR-FIN-003: Cannot post to CLOSED or LOCKED period
    await validatePeriodForPosting(tx, companyId, existing.periodId);

    // Validate accounts: active, postable, control account check for MANUAL (AC-13)
    const isManual = existing.source === 'MANUAL';
    await validateAccountsForPosting(
      tx,
      companyId,
      lines.map((l) => l.accountCode),
      isManual,
    );

    // AC-12: Enforce DimensionRequirement rules
    await validateDimensionRequirements(tx, companyId, lines);

    // BR-FIN-DIM-001: Single-select dimension constraint
    await validateSingleSelectDimensions(tx, lines);

    // Transition to POSTED (AC-3)
    const posted = await tx.journalEntry.update({
      where: { id },
      data: {
        status: 'POSTED',
        postedAt: new Date(),
        postedBy: userId,
        totalDebit,
        totalCredit,
      },
      select: DETAIL_SELECT,
    });

    // AC-4: Update account balances
    await updateAccountBalances(tx, companyId, lines);

    // AC-5: Update dimension balances
    await updateDimensionBalances(tx, companyId, existing.periodId, lines);

    return posted;
  });

  // AC-6: Emit journal.posted event
  eventBus.emit('journal.posted', {
    journalEntryId: entry.id,
    entryNumber: entry.entryNumber,
    source: entry.source,
    sourceId: entry.sourceId ?? undefined,
    sourceReference: entry.sourceReference ?? undefined,
    transactionDate: toDateString(entry.transactionDate),
    periodId: entry.periodId,
    totalAmount: String(toNumber(entry.totalDebit as unknown as Prisma.Decimal)),
    lineCount: entry.lines.length,
    createdBy: userId,
  });

  return normaliseDetail(entry as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// reverseJournalEntry (AC-7)
// ---------------------------------------------------------------------------

export async function reverseJournalEntry(
  prisma: PrismaClient,
  eventBus: EventBus,
  companyId: string,
  id: string,
  userId: string,
) {
  const { original, reversal } = await prisma.$transaction(async (tx) => {
    // Fetch the original entry with lines
    const existing = await tx.journalEntry.findFirst({
      where: { id, companyId },
      select: {
        id: true,
        entryNumber: true,
        status: true,
        source: true,
        sourceId: true,
        sourceReference: true,
        transactionDate: true,
        description: true,
        reference: true,
        periodId: true,
        lines: {
          select: {
            accountCode: true,
            description: true,
            debit: true,
            credit: true,
            vatCode: true,
            currencyCode: true,
            foreignAmount: true,
            exchangeRate: true,
            dimensions: { select: { dimensionValueId: true } },
          },
          orderBy: { lineNumber: 'asc' },
        },
      },
    });

    if (!existing) {
      throw new NotFoundError('NOT_FOUND', 'Journal entry not found');
    }

    // Only POSTED entries can be reversed
    if (existing.status !== 'POSTED') {
      throw new DomainError(
        'INVALID_STATUS_TRANSITION',
        `Cannot reverse a ${existing.status} entry. Only POSTED entries can be reversed (BR-FIN-011)`,
      );
    }

    // Validate period is open
    await validatePeriodForPosting(tx, companyId, existing.periodId);

    // Generate new entry number for the reversal
    const reversalEntryNumber = await nextNumber(tx, companyId, 'JOURNAL');

    // Normalise lines for processing
    const originalLines = existing.lines.map((l) => ({
      accountCode: l.accountCode,
      description: l.description,
      debit: toNumber(l.debit as unknown as Prisma.Decimal),
      credit: toNumber(l.credit as unknown as Prisma.Decimal),
      vatCode: l.vatCode,
      currencyCode: l.currencyCode,
      foreignAmount: l.foreignAmount
        ? toNumber(l.foreignAmount as unknown as Prisma.Decimal)
        : null,
      exchangeRate: l.exchangeRate ? toNumber(l.exchangeRate as unknown as Prisma.Decimal) : null,
      dimensions: l.dimensions,
    }));

    // Create reversal entry with negated amounts (mirror entry)
    const totalDebit = originalLines.reduce((sum, l) => sum + l.credit, 0); // swap debit/credit
    const totalCredit = originalLines.reduce((sum, l) => sum + l.debit, 0);

    const reversalEntry = await tx.journalEntry.create({
      data: {
        companyId,
        entryNumber: reversalEntryNumber,
        transactionDate: existing.transactionDate,
        description: `Reversal of ${existing.entryNumber}: ${existing.description}`,
        reference: existing.reference,
        source: existing.source,
        sourceId: existing.sourceId,
        sourceReference: existing.sourceReference,
        isAutoGenerated: true,
        status: 'POSTED',
        postedAt: new Date(),
        postedBy: userId,
        reversalOfId: existing.id,
        periodId: existing.periodId,
        totalDebit,
        totalCredit,
        createdBy: userId,
        updatedBy: userId,
      },
      select: { id: true },
    });

    // Create reversal lines (debit ↔ credit swapped)
    const reversalLines: Array<{
      accountCode: string;
      debit: number;
      credit: number;
      dimensions: Array<{ dimensionValueId: string }>;
    }> = [];

    for (let i = 0; i < originalLines.length; i++) {
      const origLine = originalLines[i]!;
      const createdLine = await tx.journalLine.create({
        data: {
          journalEntryId: reversalEntry.id,
          lineNumber: i + 1,
          accountCode: origLine.accountCode,
          companyId,
          description: origLine.description,
          debit: origLine.credit, // Swap: original credit becomes reversal debit
          credit: origLine.debit, // Swap: original debit becomes reversal credit
          vatCode: origLine.vatCode,
          currencyCode: origLine.currencyCode,
          foreignAmount: origLine.foreignAmount ? -origLine.foreignAmount : null,
          exchangeRate: origLine.exchangeRate,
        },
        select: { id: true },
      });

      // Copy dimensions
      if (origLine.dimensions.length > 0) {
        for (const dim of origLine.dimensions) {
          await tx.journalLineDimension.create({
            data: {
              journalLineId: createdLine.id,
              dimensionValueId: dim.dimensionValueId,
            },
          });
        }
      }

      reversalLines.push({
        accountCode: origLine.accountCode,
        debit: origLine.credit,
        credit: origLine.debit,
        dimensions: origLine.dimensions,
      });
    }

    // Mark original as REVERSED
    await tx.journalEntry.update({
      where: { id: existing.id },
      data: { status: 'REVERSED' },
    });

    // Update account balances for the reversal
    await updateAccountBalances(tx, companyId, reversalLines);

    // Update dimension balances for the reversal
    await updateDimensionBalances(tx, companyId, existing.periodId, reversalLines);

    // Fetch the complete reversal entry
    const fullReversal = await tx.journalEntry.findUniqueOrThrow({
      where: { id: reversalEntry.id },
      select: DETAIL_SELECT,
    });

    return { original: existing, reversal: fullReversal };
  });

  // Emit events
  eventBus.emit('journal.reversed', {
    journalEntryId: original.id,
    reversalEntryId: reversal.id,
    originalSource: original.source,
    sourceReference: original.sourceReference ?? undefined,
    createdBy: userId,
  });

  return normaliseDetail(reversal as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// createGlPosting (AC-10) — Reusable service for sub-module posting
// ---------------------------------------------------------------------------

/**
 * Reusable GL posting service callable by sub-modules (AR, AP, Stock, Payroll, etc.).
 *
 * When source=MANUAL, creates as DRAFT (caller must post separately).
 * When source is anything else (sub-module), creates directly as POSTED (BR-FIN-018).
 */
export async function createGlPosting(
  prisma: PrismaClient,
  eventBus: EventBus,
  companyId: string,
  input: GlPostingInput,
  userId: string,
) {
  const isManual = input.source === 'MANUAL';

  const entry = await prisma.$transaction(async (tx) => {
    // Determine period from transaction date
    const period = await tx.financialPeriod.findFirst({
      where: {
        companyId,
        startDate: { lte: input.transactionDate },
        endDate: { gte: input.transactionDate },
      },
      select: { id: true, status: true },
      orderBy: { periodNumber: 'asc' },
    });

    if (!period) {
      throw new NotFoundError(
        'PERIOD_NOT_FOUND',
        'No financial period found for the transaction date',
      );
    }

    // For sub-module posting (non-MANUAL), validate period is open
    if (!isManual) {
      if (period.status === 'CLOSED' || period.status === 'LOCKED') {
        throw new DomainError(
          'PERIOD_NOT_OPEN',
          `Cannot post to ${period.status.toLowerCase()} period (BR-FIN-003)`,
        );
      }
    }

    // Multi-currency conversion (E14-S20): convert foreign currency lines to base currency
    const baseCurrencyCode = await getBaseCurrencyCode(tx, companyId);
    const convertedLines = await convertLinesToBaseCurrency(
      tx,
      companyId,
      baseCurrencyCode,
      input.transactionDate,
      input.lines.map((l) => ({
        ...l,
        debit: l.debit ?? 0,
        credit: l.credit ?? 0,
      })),
    );

    // BR-FIN-001: Validate balance (on base currency amounts)
    const totalDebit = convertedLines.reduce((sum, l) => sum + l.debit, 0);
    const totalCredit = convertedLines.reduce((sum, l) => sum + l.credit, 0);
    if (Math.abs(totalDebit - totalCredit) > 0.0001) {
      throw new DomainError(
        'ENTRY_NOT_BALANCED',
        `Journal entry is not balanced: debits (${String(totalDebit)}) != credits (${String(totalCredit)}) (BR-FIN-001)`,
      );
    }

    // Validate accounts
    await validateAccountsForPosting(
      tx,
      companyId,
      convertedLines.map((l) => l.accountCode),
      isManual,
    );

    // Validate dimensions
    await validateDimensionRequirements(tx, companyId, convertedLines);
    await validateSingleSelectDimensions(tx, convertedLines);

    // Generate entry number
    const entryNumber = await nextNumber(tx, companyId, 'JOURNAL');

    // Determine status: DRAFT for manual, POSTED for sub-module (BR-FIN-018)
    const status = isManual ? 'DRAFT' : 'POSTED';
    const now = new Date();

    // Create journal entry
    const journalEntry = await tx.journalEntry.create({
      data: {
        companyId,
        entryNumber,
        transactionDate: input.transactionDate,
        description: input.description,
        reference: input.reference ?? null,
        source: input.source as JournalSourceEnum,
        sourceId: input.sourceId ?? null,
        sourceReference: input.sourceReference ?? null,
        isAutoGenerated: !isManual,
        status,
        postedAt: isManual ? null : now,
        postedBy: isManual ? null : userId,
        periodId: period.id,
        totalDebit,
        totalCredit,
        createdBy: userId,
        updatedBy: userId,
      },
      select: { id: true },
    });

    // Create lines (using converted base-currency amounts)
    for (let i = 0; i < convertedLines.length; i++) {
      const line = convertedLines[i]!;
      const originalLine = input.lines[i]!;
      const createdLine = await tx.journalLine.create({
        data: {
          journalEntryId: journalEntry.id,
          lineNumber: i + 1,
          accountCode: line.accountCode,
          companyId,
          description: line.description ?? null,
          debit: line.debit,
          credit: line.credit,
          vatCode: line.vatCode ?? null,
          currencyCode: line.currencyCode ?? null,
          foreignAmount: line.foreignAmount ?? null,
          exchangeRate: line.exchangeRate ?? null,
        },
        select: { id: true },
      });

      if (originalLine.dimensions && originalLine.dimensions.length > 0) {
        for (const dim of originalLine.dimensions) {
          await tx.journalLineDimension.create({
            data: {
              journalLineId: createdLine.id,
              dimensionValueId: dim.dimensionValueId,
            },
          });
        }
      }
    }

    // If posting directly (sub-module), update balances (using converted amounts)
    if (!isManual) {
      await updateAccountBalances(tx, companyId, convertedLines);
      await updateDimensionBalances(tx, companyId, period.id, convertedLines);
    }

    // Fetch the complete entry
    return tx.journalEntry.findUniqueOrThrow({
      where: { id: journalEntry.id },
      select: DETAIL_SELECT,
    });
  });

  // Emit events
  if (!isManual) {
    eventBus.emit('journal.posted', {
      journalEntryId: entry.id,
      entryNumber: entry.entryNumber,
      source: entry.source,
      sourceId: entry.sourceId ?? undefined,
      sourceReference: entry.sourceReference ?? undefined,
      transactionDate: toDateString(entry.transactionDate),
      periodId: entry.periodId,
      totalAmount: String(toNumber(entry.totalDebit as unknown as Prisma.Decimal)),
      lineCount: entry.lines.length,
      createdBy: userId,
    });
  } else {
    eventBus.emit('journal.created', {
      journalEntryId: entry.id,
      entryNumber: entry.entryNumber,
      companyId,
      source: 'MANUAL',
      createdBy: userId,
    });
  }

  return normaliseDetail(entry as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// getJournalEntryById
// ---------------------------------------------------------------------------

export async function getJournalEntryById(prisma: PrismaClient, companyId: string, id: string) {
  const entry = await prisma.journalEntry.findFirst({
    where: { id, companyId },
    select: DETAIL_SELECT,
  });

  if (!entry) {
    throw new NotFoundError('NOT_FOUND', 'Journal entry not found');
  }

  return normaliseDetail(entry as unknown as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// listJournalEntries (AC-11)
// ---------------------------------------------------------------------------

export async function listJournalEntries(
  prisma: PrismaClient,
  companyId: string,
  query: ListJournalsQuery,
) {
  const { cursor, limit, status, source, periodId, dateFrom, dateTo } = query;

  const where: Record<string, unknown> = { companyId };
  if (status !== undefined) where.status = status;
  if (source !== undefined) where.source = source;
  if (periodId !== undefined) where.periodId = periodId;
  if (dateFrom || dateTo) {
    const dateFilter: Record<string, unknown> = {};
    if (dateFrom) dateFilter.gte = dateFrom;
    if (dateTo) dateFilter.lte = dateTo;
    where.transactionDate = dateFilter;
  }

  const [items, total] = await Promise.all([
    prisma.journalEntry.findMany({
      where,
      take: limit + 1,
      ...(cursor ? { skip: 1, cursor: { id: cursor } } : {}),
      orderBy: [{ transactionDate: 'desc' }, { entryNumber: 'desc' }],
      select: LIST_SELECT,
    }),
    prisma.journalEntry.count({ where }),
  ]);

  const hasMore = items.length > limit;
  const data = hasMore ? items.slice(0, -1) : items;
  const nextCursor = hasMore ? data[data.length - 1]?.id : undefined;

  const mapped = data.map((row) => normaliseListItem(row as unknown as Record<string, unknown>));

  const meta: PaginationMeta = { cursor: nextCursor, hasMore, total };

  return { data: mapped, meta };
}

// ---------------------------------------------------------------------------
// searchJournalEntries (AC-11)
// ---------------------------------------------------------------------------

export async function searchJournalEntries(
  prisma: PrismaClient,
  companyId: string,
  query: SearchJournalsQuery,
) {
  const { search, status, source, limit } = query;

  const where: Record<string, unknown> = {
    companyId,
    OR: [
      { entryNumber: { contains: search, mode: 'insensitive' } },
      { description: { contains: search, mode: 'insensitive' } },
      { reference: { contains: search, mode: 'insensitive' } },
    ],
  };

  if (status !== undefined) where.status = status;
  if (source !== undefined) where.source = source;

  const items = await prisma.journalEntry.findMany({
    where,
    take: limit,
    orderBy: [{ transactionDate: 'desc' }, { entryNumber: 'desc' }],
    select: LIST_SELECT,
  });

  return items.map((row) => normaliseListItem(row as unknown as Record<string, unknown>));
}
