/**
 * TypeScript interfaces for the Journal Entry API.
 *
 * Mirrors the backend journal schemas from journals.schema.ts.
 */

// ---------------------------------------------------------------------------
// Enum constants
// ---------------------------------------------------------------------------

export const JOURNAL_SOURCES = [
  'MANUAL',
  'AR_INVOICE',
  'AR_CREDIT_NOTE',
  'AR_PAYMENT',
  'AP_BILL',
  'AP_CREDIT_NOTE',
  'AP_PAYMENT',
  'BANK_PAYMENT',
  'BANK_RECEIPT',
  'BANK_TRANSFER',
  'STOCK_MOVEMENT',
  'STOCK_REVALUATION',
  'GOODS_RECEIPT',
  'SHIPMENT',
  'DEPRECIATION',
  'PAYROLL',
  'PRODUCTION',
  'VAT_ADJUSTMENT',
  'YEAR_END',
  'OPENING_BALANCE',
] as const;

export type JournalSource = (typeof JOURNAL_SOURCES)[number];

export const JOURNAL_STATUSES = ['DRAFT', 'POSTED', 'REVERSED'] as const;

export type JournalStatus = (typeof JOURNAL_STATUSES)[number];

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export interface JournalLineDimension {
  id: string;
  dimensionValueId: string;
  dimensionValue?: {
    id: string;
    code: string;
    name: string;
    dimensionType: {
      id: string;
      code: string;
      name: string;
    };
  };
}

export interface JournalLine {
  id: string;
  lineNumber: number;
  accountCode: string;
  description: string | null;
  debit: number;
  credit: number;
  vatCode: string | null;
  currencyCode: string | null;
  foreignAmount: number | null;
  exchangeRate: number | null;
  dimensions?: JournalLineDimension[];
}

export interface JournalListItem {
  id: string;
  entryNumber: string;
  transactionDate: string;
  description: string;
  reference: string | null;
  source: JournalSource;
  sourceReference: string | null;
  status: JournalStatus;
  periodId: string;
  totalDebit: number;
  totalCredit: number;
  postedAt: string | null;
  postedBy: string | null;
  reversalOfId: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface JournalDetail extends JournalListItem {
  sourceId: string | null;
  templateId: string | null;
  createdBy: string;
  updatedBy: string;
  lines: JournalLine[];
}

// ---------------------------------------------------------------------------
// Request types (line input)
// ---------------------------------------------------------------------------

export interface JournalLineInput {
  accountCode: string;
  description?: string;
  debit: number;
  credit: number;
  vatCode?: string;
  currencyCode?: string;
  foreignAmount?: number;
  exchangeRate?: number;
  dimensions?: Array<{ dimensionValueId: string }>;
}

export interface CreateJournalInput {
  transactionDate: string;
  description: string;
  reference?: string;
  periodId: string;
  lines: JournalLineInput[];
}

export interface UpdateJournalInput {
  transactionDate?: string;
  description?: string;
  reference?: string | null;
  periodId?: string;
  lines?: JournalLineInput[];
}

// ---------------------------------------------------------------------------
// List params
// ---------------------------------------------------------------------------

export interface ListJournalsParams {
  status?: JournalStatus;
  source?: JournalSource;
  periodId?: string;
  dateFrom?: string;
  dateTo?: string;
  cursor?: string;
  limit?: number;
}
