/* eslint-disable i18next/no-literal-string */
/**
 * AttachmentPreview — card showing attached file details.
 *
 * Purple-tinted card styling per Concept D (12px radius, custom shadow).
 * Shows file icon, filename, file size, and optional auto-generated badge.
 *
 * E10-3 Task 5.4
 */

import { FileText, X } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, i)).toFixed(i > 0 ? 1 : 0)} ${units[i]}`;
}

interface AttachmentPreviewProps {
  fileName: string;
  fileSize?: number;
  isAutoGenerated?: boolean;
  onRemove?: () => void;
  disabled?: boolean;
}

export function AttachmentPreview({
  fileName,
  fileSize,
  isAutoGenerated = true,
  onRemove,
  disabled = false,
}: AttachmentPreviewProps) {
  return (
    <div
      className={cn(
        'flex items-center gap-3 rounded-xl border bg-white p-3',
        'shadow-[0_1px_3px_rgba(0,0,0,0.06)]',
        'hover:shadow-[0_4px_12px_rgba(124,58,237,0.1)]',
        'transition-shadow',
      )}
    >
      {/* PDF icon */}
      <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-red-50">
        <FileText className="size-5 text-red-600" />
      </div>

      {/* File details */}
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-medium text-foreground">{fileName}</p>
        <div className="flex items-center gap-2">
          {fileSize != null && (
            <span className="text-xs text-muted-foreground">{formatFileSize(fileSize)}</span>
          )}
          {isAutoGenerated && (
            <Badge
              variant="secondary"
              className="border-0 bg-[#7c3aed]/10 text-[#7c3aed] text-[10px] px-1.5 py-0"
            >
              Auto-generated
            </Badge>
          )}
        </div>
      </div>

      {/* Remove button */}
      {onRemove && (
        <button
          type="button"
          onClick={onRemove}
          disabled={disabled}
          className={cn(
            'rounded-full p-1 text-muted-foreground transition-colors',
            'hover:bg-red-50 hover:text-red-600',
            disabled && 'opacity-50 pointer-events-none',
          )}
          aria-label={`Remove ${fileName}`}
        >
          <X className="size-4" />
        </button>
      )}
    </div>
  );
}
