// ---------------------------------------------------------------------------
// Email Zod Schemas — E10-1 Task 6.1
// Validation schemas for the /email/messages REST API endpoints.
// ---------------------------------------------------------------------------

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Enums (mirror Prisma enums for Zod validation)
// ---------------------------------------------------------------------------

const emailMessageStatusEnum = z.enum(['DRAFT', 'QUEUED', 'SENT', 'FAILED', 'BOUNCED']);
const emailDirectionEnum = z.enum(['INBOUND', 'OUTBOUND']);
const emailRecipientTypeEnum = z.enum(['FROM', 'TO', 'CC', 'BCC']);
const emailRecipientStatusEnum = z.enum(['UNREAD', 'READ', 'DELETED', 'ARCHIVED']);
const emailQueueStatusEnum = z.enum(['PENDING', 'PROCESSING', 'SENT', 'FAILED', 'RETRYING']);

// ---------------------------------------------------------------------------
// Request Schemas
// ---------------------------------------------------------------------------

/** GET /email/messages — query parameters */
export const listEmailsQuerySchema = z.object({
  status: emailMessageStatusEnum.optional(),
  direction: emailDirectionEnum.optional(),
  sourceEntityType: z.string().max(100).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().optional(),
});

/** Path params for /:id endpoints */
export const emailIdParamsSchema = z.object({
  id: z.uuid(),
});

/** POST /email/messages — request body */
export const createEmailBodySchema = z.object({
  subject: z.string().min(1).max(500),
  bodyText: z.string().optional(),
  bodyHtml: z.string().optional(),
  recipients: z
    .array(
      z.object({
        recipientType: emailRecipientTypeEnum,
        emailAddress: z.string().min(1).max(320),
        userId: z.string().optional(),
        displayName: z.string().max(200).optional(),
      }),
    )
    .min(1)
    .refine((recipients) => recipients.some((r) => r.recipientType === 'TO'), {
      message: 'At least one TO recipient is required',
    }),
  sourceEntityType: z.string().max(100).optional(),
  sourceEntityId: z.string().optional(),
  emailTemplateId: z.string().optional(),
  priority: z.number().int().min(0).max(1).optional(),
});

// ---------------------------------------------------------------------------
// Response Schemas
// ---------------------------------------------------------------------------

const emailRecipientResponseSchema = z.object({
  id: z.string(),
  recipientType: emailRecipientTypeEnum,
  emailAddress: z.string(),
  displayName: z.string().nullable(),
  userId: z.string().nullable(),
  status: emailRecipientStatusEnum,
  readAt: z.date().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

const emailQueueResponseSchema = z.object({
  id: z.string(),
  status: emailQueueStatusEnum,
  priority: z.number().int(),
  attempts: z.number().int(),
  maxAttempts: z.number().int(),
  lastError: z.string().nullable(),
  nextRetryAt: z.date().nullable(),
  smtpResponse: z.string().nullable(),
  deliveredAt: z.date().nullable(),
  queuedAt: z.date(),
  processedAt: z.date().nullable(),
});

export const emailResponseSchema = z.object({
  id: z.string(),
  messageNumber: z.string(),
  subject: z.string(),
  bodyText: z.string().nullable(),
  bodyHtml: z.string().nullable(),
  direction: emailDirectionEnum,
  status: emailMessageStatusEnum,
  externalMessageId: z.string().nullable(),
  inReplyTo: z.string().nullable(),
  threadId: z.string().nullable(),
  sourceEntityType: z.string().nullable(),
  sourceEntityId: z.string().nullable(),
  emailTemplateId: z.string().nullable(),
  priority: z.number().int(),
  isHtml: z.boolean(),
  hasAttachments: z.boolean(),
  isAutoGenerated: z.boolean(),
  isBounce: z.boolean(),
  isMailingList: z.boolean(),
  sentAt: z.date().nullable(),
  companyId: z.string(),
  createdBy: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  recipients: z.array(emailRecipientResponseSchema),
  queueEntry: emailQueueResponseSchema.nullable(),
});

/** Lighter response for list endpoint (includes recipient summary + queue status) */
const emailListItemSchema = z.object({
  id: z.string(),
  messageNumber: z.string(),
  subject: z.string(),
  direction: emailDirectionEnum,
  status: emailMessageStatusEnum,
  sourceEntityType: z.string().nullable(),
  sourceEntityId: z.string().nullable(),
  priority: z.number().int(),
  isHtml: z.boolean(),
  hasAttachments: z.boolean(),
  sentAt: z.date().nullable(),
  createdBy: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  recipients: z.array(
    z.object({
      id: z.string(),
      recipientType: emailRecipientTypeEnum,
      emailAddress: z.string(),
      displayName: z.string().nullable(),
    }),
  ),
  queueEntry: z
    .object({
      id: z.string(),
      status: emailQueueStatusEnum,
      attempts: z.number().int(),
      lastError: z.string().nullable(),
    })
    .nullable(),
});

export const emailListResponseSchema = z.object({
  items: z.array(emailListItemSchema),
  meta: z.object({
    cursor: z.string().nullable(),
    hasMore: z.boolean(),
  }),
});

export const deleteEmailResponseSchema = z.object({
  deleted: z.boolean(),
});

// ---------------------------------------------------------------------------
// Inferred TypeScript Types
// ---------------------------------------------------------------------------

export type ListEmailsQuery = z.infer<typeof listEmailsQuerySchema>;
export type EmailIdParams = z.infer<typeof emailIdParamsSchema>;
export type CreateEmailBody = z.infer<typeof createEmailBodySchema>;
export type EmailResponse = z.infer<typeof emailResponseSchema>;
